name: ci

on: [push, pull_request]

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -e .[pre-commit,tests]
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        pip install -e .[tests]
    - name: Run tests
      run: pytest --cov-report xml
    - name: Upload coverage report
      if: github.repository == 'ltalirz/isotherm-digitizer-panel'
      uses: codecov/codecov-action@v1
      with:
        name: ubuntu-apt
        file: ./coverage.xml
        fail_ci_if_error: true
